<MainScreen>
    Label:
        text: "Bienvenido al juego del Ahorcadito"

    BoxLayout:
        orientacion: 'horizontal'
        Button:
            text: "Jugar"
            size_hint: 0.3, 0.2
            on_press: root.abrir_pantalla_de_juego()
        
        Button:
            text: "Configurar"
            size_hint: 0.3, 0.2

        Button:
            text: "Salir"
            size_hint: 0.3, 0.2